# Generated by Django 3.2.5 on 2021-08-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='takenexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_exams', to='school.exam'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='school.answer'),
        ),
        migrations.AddField(
            model_name='takenexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taken_exams', to='account.student'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answeres', to='account.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='exams',
            field=models.ManyToManyField(through='account.TakenExam', to='school.Exam'),
        ),
    ]
