# Generated by Django 3.2.5 on 2021-07-16 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_school_grade'),
        ('account', '0002_alter_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='taken_exams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_exams', to='school.exam'),
        ),
    ]
