# Generated by Django 3.2.5 on 2021-07-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_school_grade'),
        ('account', '0003_alter_student_taken_exams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='taken_exams',
        ),
        migrations.AddField(
            model_name='student',
            name='taken_exams',
            field=models.ManyToManyField(blank=True, null=True, related_name='taken_exams', to='school.Exam'),
        ),
    ]
