# Generated by Django 3.2.5 on 2021-07-21 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takenexam',
            old_name='studen',
            new_name='student',
        ),
    ]
