# Generated by Django 3.2.5 on 2021-07-19 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210716_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='taken_exams',
        ),
    ]
