# Generated by Django 3.2.5 on 2021-08-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='questions/answares/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='questions/question/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='school',
            field=models.ManyToManyField(related_name='school', to='school.School'),
        ),
    ]
