# Generated by Django 3.2.5 on 2021-07-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='course',
            field=models.CharField(default=2021, max_length=220),
            preserve_default=False,
        ),
    ]
