# Generated by Django 3.2.5 on 2021-07-19 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='exams',
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.OneToOneField(default=2021, on_delete=django.db.models.deletion.CASCADE, to='school.subject'),
            preserve_default=False,
        ),
    ]
