# Generated by Django 3.2.5 on 2021-07-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_school_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answare',
            field=models.ForeignKey(default=2021, on_delete=django.db.models.deletion.CASCADE, to='school.answare'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(default=2021, on_delete=django.db.models.deletion.CASCADE, to='school.exam'),
            preserve_default=False,
        ),
    ]
