# Generated by Django 3.2.5 on 2021-07-20 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('school', '0002_alter_exam_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='account.teacher'),
        ),
    ]
