# Generated by Django 3.2.5 on 2021-07-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20210719_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ManyToManyField(to='school.School'),
        ),
    ]
