# Generated by Django 3.2.5 on 2021-07-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_school_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=2021),
            preserve_default=False,
        ),
    ]
