# Generated by Django 3.2.5 on 2021-07-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20210714_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answare',
        ),
        migrations.AddField(
            model_name='answare',
            name='question',
            field=models.ForeignKey(default=2021, on_delete=django.db.models.deletion.CASCADE, to='school.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='required_score_to_pass',
            field=models.IntegerField(default=1, help_text='required score in %'),
            preserve_default=False,
        ),
    ]
